project:
  type: website
  output-dir: docs

website:
  title: "Leam Howe"
  favicon: images/mountain_sketch_icon.png
  navbar:
    left:
      - href: index.qmd
        # html: "<img src='images/ML4GEO_logo.png' alt='ML4GEO Logo' style='height: 40px;'>"
        text: Home
      - href: phd-project.qmd
        text: PhD Project
      - href: blogs.qmd
        text: Blog
      # - about.qmd
      # - href: events.qmd
      # - href: committee.qmd
      # - href: members.qmd
      # - href: resources.qmd

format:
  html:
    theme:
      - cosmo
      # - [cosmo, styles.css]
      - brand
    css: 
      - /styles.css
      - /styles.css
    # background-color: #EBDFCC 
    toc: true


# resources:
#   - _site/styles.css
resources:
  - /styles.css

# format:
#   html:
#     include-after-body:
#       - html: |
#           <link href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.7.1/css/lightgallery.min.css" rel="stylesheet">
#           <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.7.1/lightgallery.min.js"></script>
#           <script src="https://cdnjs.cloudflare.com/ajax/libs/lg-zoom/2.7.1/lg-zoom.min.js"></script>
